account/urls.py
from django.urls import path
from .views import signup,signin
app_name='accounts'
urlpatterns=[
    path('signup/',signup,name='signup'),
    path('signin/',signin,name='signin'),
]

coreapi/urls.py
from . import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('account.urls',namespace='accounts')),
    path('',include(('imageapi.urls','home'),namespace='home')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

imageapi/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns=[
    path('',views.home,name='home'),
    path('allimages/',views.all_images,name='image'),
    path('api/<int:id>/',views.api_service,name='api'),
]

account/models.py
from django.db import models

from django.contrib.auth.models import User



class ApiKey(models.Model):
    user=models.ForeignKey( User, on_delete=models.CASCADE)
    key=models.CharField(max_length=260)


    def __str__(self):
        return self.user.username
    
    def __str__(self):
        return self.key


# Create your models here.
class Photo(models.Model):
    user=models.ForeignKey(User, on_delete=models.PROTECT)
    caption=models.CharField(max_length=60)
    picture=models.ImageField(upload_to='images')
    


    def __str__(self):
        return self.caption

imageapi/models.py
from django.db import models

# Create your models here.

account/forms.py
from django.contrib.auth.forms import UserCreationForm 

from django import forms

from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):


    class Meta:
        model=User
        fields=['username','email','password1','password2']

account/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import RegisterForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import authenticate,login,logout
from .models import ApiKey
# Create your views here.
def signup(request):
    if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            user=form.save()
            
            key=default_token_generator.make_token(user)
            api=ApiKey.objects.create (user=user,key=key)
            api.save()
            return redirect('accounts:signin')
        return render (request,'register.html',{'form':form})    

    form=RegisterForm()
    return render (request,'register.html',{'form': form})    

def signin(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        print("hello")
        user=authenticate(request,username=username,password=password)
        if user:
            login(request, user)
            return HttpResponse("Succesfully Logged in")
        return HttpResponse('incorect username or password')    
     
    return render (request,'login.html')

imageapi/views.py
from django.shortcuts import render,HttpResponse
from django.template import RequestContext, Template, Context
from django.conf import settings
from account.models import Photo
from django.contrib.staticfiles.urls import static

# Create your views here.
def home(request):
    return render (request, 'index.html')


def all_images(request):
    images=Photo.objects.all()
    context={'images':images}
    return render (request, 'allimages.html',context)



def api_service(request,id):
    images=Photo.objects.get(id=id)
    k=images.picture.url
    print(k)
    
    return HttpResponse(f' <img src=" { k }" alt="hi" width=200px height=200px > ')

templates/allimages.html
{% extends 'index.html' %}


{% block content  %}
    <div style="display:flex; padding:30px;justify-content:space-between;align-items:center">


 {% for i in images %} 
 <div style="border:2px solid white;height:300px;width:300px;border-radius:10px ;overflow: hidden;text-align: center;" >
    <img src="{{ i.picture.url }}" style="width:300px;height:200px;">
    <p>Caption:{{ i.caption }}</p>
    <p><a href="{% url 'home:api' i.id %}">{{ i.id }} </a></p>

 </div>
{% endfor %}
</div>

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<body>
    <header>
        <h2 class="home">
            ImageApi
        </h2>
        <nav class="navs">
            <ul>
                <li>
                    <a href="#">Home</a>
                </li>
                <li>
                    <a href="#">All images</a>
                </li>
                <li>
                    <a href="#">Image Upload </a>
                </li>
            </ul>

        </nav>
        <button class="logout">
            Logout
        </button>
    </header>
    {% block content %}

    <div>
        <h1>hello</h1>
        <img src="http://127.0.0.1:8000/api/1/" alt="hi" />
    </div>
    
    {% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> SignIn </title>
</head>

<body style="margin:0;padding:0;background-color: black;">

    <div style="height:100vh;width:100vw;display:flex;justify-content:center;align-items:center;">
        <div style="background-color: aquamarine;height:400px;width:250px;text-align:center;border-radius:15px;position:relative;">
            <h2 style="margin-top: 70px;">SignIn</h2>
            <div style="display:flex;justify-content:center;align-items:center;margin-top:50px;">

                <div >
                    <form action="" method="post">
                        {% csrf_token %}


                        <p> Username:<input type="text" name="username"></p>
                        <p>Password:<input type="password" name="password"></p>
                        <input type="submit" value="Login">

                    </form>

                    

                </div>

            </div>
            <a href="{% url 'accounts:signup' }" style="left:25%;bottom:15px;position: absolute;">Create an Account</a>
        </div>

    </div>

</body>

</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body style="margin: 0;padding: 0 ;background-color: black;">
    <div style=" height:100vh;width:100vw;display:flex;justify-content:center;align-items:center">
        <div style="background-color: lightgray;border-radius: 10px;height:60%;display:flex;position: relative;">
            
            
                

                <div style="justify-content:center;align-items:center ;margin-top:50px ">
                    <h2 style="text-align:center">
                            SignUp
                    </h2>




                


                    <form action="" method="POST">
                        {% csrf_token %}
                        <table style="border-collapse: separate;border-spacing:15px ;margin: 0 auto;">
                            <tr>

                                <td> <label for="">Username</label></td>
                                <td>{{form.username}}</td>

                            </tr>
                            <tr>


                                <td> <label for="">Email</label></td>
                                <td>{{form.email}}</td>

                            </tr>
                            <tr>

                                <td> <label>Password</label></td>
                                <td> {{form.password1}}</td>

                            </tr>
                            <tr>

                                <td> <label>Password</label></td>
                                <td>{{form.password2}} </td>

                            </tr>

                            <tr>
                                <td colspan="2" align="center">
                                    <input type="submit" value="Register">
                                </td>
                            </tr>


                        </table>


                    </form>
                </div>

            
        </div>

    </div>





</body>

</html>